// Genealogy data for 1 Chronicles 1–2
// Flat array — built into a tree via d3.stratify()
// id: unique key  |  pid: parent id (null = root)
// spine: on the Adam→David redemptive line
// david: the destination node
// note: extra detail shown in tooltip

const nodes = [

  // ── PRE-FLOOD SPINE (1Ch 1:1-4) ─────────────────────────────────────────
  {id:"adam",        pid:null,      name:"Adam",        ref:"1Ch 1:1",  spine:true},
  {id:"seth",        pid:"adam",    name:"Seth",        ref:"1Ch 1:1",  spine:true},
  {id:"enosh",       pid:"seth",    name:"Enosh",       ref:"1Ch 1:1",  spine:true},
  {id:"kenan",       pid:"enosh",   name:"Kenan",       ref:"1Ch 1:2",  spine:true},
  {id:"mahalalel",   pid:"kenan",   name:"Mahalalel",   ref:"1Ch 1:2",  spine:true},
  {id:"jared",       pid:"mahalalel",name:"Jared",      ref:"1Ch 1:2",  spine:true},
  {id:"enoch",       pid:"jared",   name:"Enoch",       ref:"1Ch 1:3",  spine:true},
  {id:"methuselah",  pid:"enoch",   name:"Methuselah",  ref:"1Ch 1:3",  spine:true},
  {id:"lamech",      pid:"methuselah",name:"Lamech",    ref:"1Ch 1:3",  spine:true},
  {id:"noah",        pid:"lamech",  name:"Noah",        ref:"1Ch 1:4",  spine:true},

  // ── SONS OF JAPHETH (1Ch 1:4-7) ─────────────────────────────────────────
  {id:"japheth",     pid:"noah",    name:"Japheth",     ref:"1Ch 1:4"},
  {id:"gomer",       pid:"japheth", name:"Gomer",       ref:"1Ch 1:5"},
  {id:"magog",       pid:"japheth", name:"Magog",       ref:"1Ch 1:5"},
  {id:"madai",       pid:"japheth", name:"Madai",       ref:"1Ch 1:5"},
  {id:"javan",       pid:"japheth", name:"Javan",       ref:"1Ch 1:5"},
  {id:"tubal",       pid:"japheth", name:"Tubal",       ref:"1Ch 1:5"},
  {id:"meshech-j",   pid:"japheth", name:"Meshech",     ref:"1Ch 1:5"},
  {id:"tiras",       pid:"japheth", name:"Tiras",       ref:"1Ch 1:5"},
  {id:"ashkenaz",    pid:"gomer",   name:"Ashkenaz",    ref:"1Ch 1:6"},
  {id:"diphath",     pid:"gomer",   name:"Diphath",     ref:"1Ch 1:6"},
  {id:"togarmah",    pid:"gomer",   name:"Togarmah",    ref:"1Ch 1:6"},
  {id:"elishah",     pid:"javan",   name:"Elishah",     ref:"1Ch 1:7"},
  {id:"tarshish",    pid:"javan",   name:"Tarshish",    ref:"1Ch 1:7"},
  {id:"kittim",      pid:"javan",   name:"Kittim",      ref:"1Ch 1:7"},
  {id:"rodanim",     pid:"javan",   name:"Rodanim",     ref:"1Ch 1:7"},

  // ── SONS OF HAM (1Ch 1:8-16) ────────────────────────────────────────────
  {id:"ham",         pid:"noah",    name:"Ham",         ref:"1Ch 1:4"},
  {id:"cush",        pid:"ham",     name:"Cush",        ref:"1Ch 1:8"},
  {id:"mizraim",     pid:"ham",     name:"Mizraim",     ref:"1Ch 1:8"},
  {id:"put",         pid:"ham",     name:"Put",         ref:"1Ch 1:8"},
  {id:"canaan",      pid:"ham",     name:"Canaan",      ref:"1Ch 1:8"},
  {id:"seba",        pid:"cush",    name:"Seba",        ref:"1Ch 1:9"},
  {id:"havilah-c",   pid:"cush",    name:"Havilah",     ref:"1Ch 1:9"},
  {id:"sabta",       pid:"cush",    name:"Sabta",       ref:"1Ch 1:9"},
  {id:"raama",       pid:"cush",    name:"Raama",       ref:"1Ch 1:9"},
  {id:"sabteca",     pid:"cush",    name:"Sabteca",     ref:"1Ch 1:9"},
  {id:"nimrod",      pid:"cush",    name:"Nimrod",      ref:"1Ch 1:10", note:"mighty one in the earth"},
  {id:"sheba-r",     pid:"raama",   name:"Sheba",       ref:"1Ch 1:9"},
  {id:"dedan-r",     pid:"raama",   name:"Dedan",       ref:"1Ch 1:9"},
  {id:"ludim",       pid:"mizraim", name:"Ludim",       ref:"1Ch 1:11"},
  {id:"anamim",      pid:"mizraim", name:"Anamim",      ref:"1Ch 1:11"},
  {id:"lehabim",     pid:"mizraim", name:"Lehabim",     ref:"1Ch 1:11"},
  {id:"naphtuhim",   pid:"mizraim", name:"Naphtuhim",   ref:"1Ch 1:11"},
  {id:"pathrusim",   pid:"mizraim", name:"Pathrusim",   ref:"1Ch 1:12"},
  {id:"casluhim",    pid:"mizraim", name:"Casluhim",    ref:"1Ch 1:12", note:"Philistines came from here"},
  {id:"caphtorim",   pid:"mizraim", name:"Caphtorim",   ref:"1Ch 1:12"},
  {id:"sidon",       pid:"canaan",  name:"Sidon",       ref:"1Ch 1:13", note:"firstborn"},
  {id:"heth",        pid:"canaan",  name:"Heth",        ref:"1Ch 1:13"},
  {id:"jebusite",    pid:"canaan",  name:"Jebusite",    ref:"1Ch 1:14"},
  {id:"amorite",     pid:"canaan",  name:"Amorite",     ref:"1Ch 1:14"},
  {id:"girgashite",  pid:"canaan",  name:"Girgashite",  ref:"1Ch 1:14"},
  {id:"hivite",      pid:"canaan",  name:"Hivite",      ref:"1Ch 1:15"},
  {id:"arkite",      pid:"canaan",  name:"Arkite",      ref:"1Ch 1:15"},
  {id:"sinite",      pid:"canaan",  name:"Sinite",      ref:"1Ch 1:15"},
  {id:"arvadite",    pid:"canaan",  name:"Arvadite",    ref:"1Ch 1:16"},
  {id:"zemarite",    pid:"canaan",  name:"Zemarite",    ref:"1Ch 1:16"},
  {id:"hamathite",   pid:"canaan",  name:"Hamathite",   ref:"1Ch 1:16"},

  // ── SONS OF SHEM (1Ch 1:17-27) ──────────────────────────────────────────
  {id:"shem",        pid:"noah",    name:"Shem",        ref:"1Ch 1:4",  spine:true},
  {id:"elam",        pid:"shem",    name:"Elam",        ref:"1Ch 1:17"},
  {id:"asshur",      pid:"shem",    name:"Asshur",      ref:"1Ch 1:17"},
  {id:"arpachshad",  pid:"shem",    name:"Arpachshad",  ref:"1Ch 1:17", spine:true},
  {id:"lud",         pid:"shem",    name:"Lud",         ref:"1Ch 1:17"},
  {id:"aram",        pid:"shem",    name:"Aram",        ref:"1Ch 1:17"},
  {id:"uz-s",        pid:"shem",    name:"Uz",          ref:"1Ch 1:17"},
  {id:"hul",         pid:"shem",    name:"Hul",         ref:"1Ch 1:17"},
  {id:"gether",      pid:"shem",    name:"Gether",      ref:"1Ch 1:17"},
  {id:"meshech-s",   pid:"shem",    name:"Meshech",     ref:"1Ch 1:17"},
  {id:"shelah",      pid:"arpachshad",name:"Shelah",    ref:"1Ch 1:18", spine:true},
  {id:"eber",        pid:"shelah",  name:"Eber",        ref:"1Ch 1:18", spine:true},
  {id:"peleg",       pid:"eber",    name:"Peleg",       ref:"1Ch 1:19", spine:true, note:"in his days the earth was divided"},
  {id:"joktan",      pid:"eber",    name:"Joktan",      ref:"1Ch 1:19"},
  {id:"reu",         pid:"peleg",   name:"Reu",         ref:"1Ch 1:25", spine:true},
  {id:"serug",       pid:"reu",     name:"Serug",       ref:"1Ch 1:26", spine:true},
  {id:"nahor",       pid:"serug",   name:"Nahor",       ref:"1Ch 1:26", spine:true},
  {id:"terah",       pid:"nahor",   name:"Terah",       ref:"1Ch 1:26", spine:true},
  {id:"abraham",     pid:"terah",   name:"Abraham",     ref:"1Ch 1:27", spine:true, note:"also called Abram"},

  // Joktan's sons (1Ch 1:20-23)
  {id:"almodad",     pid:"joktan",  name:"Almodad",     ref:"1Ch 1:20"},
  {id:"sheleph",     pid:"joktan",  name:"Sheleph",     ref:"1Ch 1:20"},
  {id:"hazarmaveth", pid:"joktan",  name:"Hazarmaveth", ref:"1Ch 1:20"},
  {id:"jerah",       pid:"joktan",  name:"Jerah",       ref:"1Ch 1:20"},
  {id:"hadoram",     pid:"joktan",  name:"Hadoram",     ref:"1Ch 1:21"},
  {id:"uzal",        pid:"joktan",  name:"Uzal",        ref:"1Ch 1:21"},
  {id:"diklah",      pid:"joktan",  name:"Diklah",      ref:"1Ch 1:21"},
  {id:"ebal-j",      pid:"joktan",  name:"Ebal",        ref:"1Ch 1:22"},
  {id:"abimael",     pid:"joktan",  name:"Abimael",     ref:"1Ch 1:22"},
  {id:"sheba-j",     pid:"joktan",  name:"Sheba",       ref:"1Ch 1:22"},
  {id:"ophir",       pid:"joktan",  name:"Ophir",       ref:"1Ch 1:23"},
  {id:"havilah-j",   pid:"joktan",  name:"Havilah",     ref:"1Ch 1:23"},
  {id:"jobab-j",     pid:"joktan",  name:"Jobab",       ref:"1Ch 1:23"},

  // ── ABRAHAM'S CHILDREN ───────────────────────────────────────────────────
  {id:"ishmael",     pid:"abraham", name:"Ishmael",     ref:"1Ch 1:28"},
  {id:"keturah-sons",pid:"abraham", name:"Keturah's sons",ref:"1Ch 1:32", note:"Abraham's concubine"},
  {id:"isaac",       pid:"abraham", name:"Isaac",       ref:"1Ch 1:34", spine:true},

  // Ishmael's sons (1Ch 1:29-31)
  {id:"nebaioth",    pid:"ishmael", name:"Nebaioth",    ref:"1Ch 1:29", note:"firstborn"},
  {id:"kedar",       pid:"ishmael", name:"Kedar",       ref:"1Ch 1:29"},
  {id:"adbeel",      pid:"ishmael", name:"Adbeel",      ref:"1Ch 1:29"},
  {id:"mibsam",      pid:"ishmael", name:"Mibsam",      ref:"1Ch 1:29"},
  {id:"mishma",      pid:"ishmael", name:"Mishma",      ref:"1Ch 1:30"},
  {id:"dumah",       pid:"ishmael", name:"Dumah",       ref:"1Ch 1:30"},
  {id:"massa",       pid:"ishmael", name:"Massa",       ref:"1Ch 1:30"},
  {id:"hadad-i",     pid:"ishmael", name:"Hadad",       ref:"1Ch 1:30"},
  {id:"tema",        pid:"ishmael", name:"Tema",        ref:"1Ch 1:30"},
  {id:"jetur",       pid:"ishmael", name:"Jetur",       ref:"1Ch 1:31"},
  {id:"naphish",     pid:"ishmael", name:"Naphish",     ref:"1Ch 1:31"},
  {id:"kedemah",     pid:"ishmael", name:"Kedemah",     ref:"1Ch 1:31"},

  // Keturah's sons (1Ch 1:32-33)
  {id:"zimran",      pid:"keturah-sons", name:"Zimran", ref:"1Ch 1:32"},
  {id:"jokshan",     pid:"keturah-sons", name:"Jokshan",ref:"1Ch 1:32"},
  {id:"medan",       pid:"keturah-sons", name:"Medan",  ref:"1Ch 1:32"},
  {id:"midian",      pid:"keturah-sons", name:"Midian", ref:"1Ch 1:32"},
  {id:"ishbak",      pid:"keturah-sons", name:"Ishbak", ref:"1Ch 1:32"},
  {id:"shuah",       pid:"keturah-sons", name:"Shuah",  ref:"1Ch 1:32"},
  {id:"sheba-k",     pid:"jokshan", name:"Sheba",       ref:"1Ch 1:32"},
  {id:"dedan-k",     pid:"jokshan", name:"Dedan",       ref:"1Ch 1:32"},
  {id:"ephah-m",     pid:"midian",  name:"Ephah",       ref:"1Ch 1:33"},
  {id:"epher",       pid:"midian",  name:"Epher",       ref:"1Ch 1:33"},
  {id:"hanoch",      pid:"midian",  name:"Hanoch",      ref:"1Ch 1:33"},
  {id:"abida",       pid:"midian",  name:"Abida",       ref:"1Ch 1:33"},
  {id:"eldaah",      pid:"midian",  name:"Eldaah",      ref:"1Ch 1:33"},

  // ── ISAAC'S CHILDREN (1Ch 1:34 – 2:2) ──────────────────────────────────
  {id:"esau",        pid:"isaac",   name:"Esau",        ref:"1Ch 1:35"},
  {id:"sons-of-seir",pid:"isaac",   name:"Sons of Seir",ref:"1Ch 1:38", note:"Horite peoples of the land of Edom"},
  {id:"israel",      pid:"isaac",   name:"Israel",      ref:"1Ch 1:34", spine:true, note:"also called Jacob"},

  // Esau's sons (1Ch 1:35-37)
  {id:"eliphaz",     pid:"esau",    name:"Eliphaz",     ref:"1Ch 1:35"},
  {id:"reuel",       pid:"esau",    name:"Reuel",       ref:"1Ch 1:35"},
  {id:"jeush",       pid:"esau",    name:"Jeush",       ref:"1Ch 1:35"},
  {id:"jalam",       pid:"esau",    name:"Jalam",       ref:"1Ch 1:35"},
  {id:"korah-e",     pid:"esau",    name:"Korah",       ref:"1Ch 1:35"},
  {id:"teman",       pid:"eliphaz", name:"Teman",       ref:"1Ch 1:36"},
  {id:"omar",        pid:"eliphaz", name:"Omar",        ref:"1Ch 1:36"},
  {id:"zephi",       pid:"eliphaz", name:"Zephi",       ref:"1Ch 1:36"},
  {id:"gatam",       pid:"eliphaz", name:"Gatam",       ref:"1Ch 1:36"},
  {id:"kenaz",       pid:"eliphaz", name:"Kenaz",       ref:"1Ch 1:36"},
  {id:"timna",       pid:"eliphaz", name:"Timna",       ref:"1Ch 1:36"},
  {id:"amalek",      pid:"eliphaz", name:"Amalek",      ref:"1Ch 1:36"},
  {id:"nahath",      pid:"reuel",   name:"Nahath",      ref:"1Ch 1:37"},
  {id:"zerah-r",     pid:"reuel",   name:"Zerah",       ref:"1Ch 1:37"},
  {id:"shammah-r",   pid:"reuel",   name:"Shammah",     ref:"1Ch 1:37"},
  {id:"mizzah",      pid:"reuel",   name:"Mizzah",      ref:"1Ch 1:37"},

  // Sons of Seir (1Ch 1:38-42)
  {id:"lotan",       pid:"sons-of-seir", name:"Lotan",  ref:"1Ch 1:38"},
  {id:"shobal-s",    pid:"sons-of-seir", name:"Shobal", ref:"1Ch 1:38"},
  {id:"zibeon",      pid:"sons-of-seir", name:"Zibeon", ref:"1Ch 1:38"},
  {id:"anah-s",      pid:"sons-of-seir", name:"Anah",   ref:"1Ch 1:38"},
  {id:"dishon-s",    pid:"sons-of-seir", name:"Dishon", ref:"1Ch 1:38"},
  {id:"ezer-s",      pid:"sons-of-seir", name:"Ezer",   ref:"1Ch 1:38"},
  {id:"dishan",      pid:"sons-of-seir", name:"Dishan", ref:"1Ch 1:38"},
  {id:"hori",        pid:"lotan",   name:"Hori",        ref:"1Ch 1:39"},
  {id:"homam",       pid:"lotan",   name:"Homam",       ref:"1Ch 1:39"},
  {id:"alian",       pid:"shobal-s",name:"Alian",       ref:"1Ch 1:40"},
  {id:"manahath",    pid:"shobal-s",name:"Manahath",    ref:"1Ch 1:40"},
  {id:"ebal-s",      pid:"shobal-s",name:"Ebal",        ref:"1Ch 1:40"},
  {id:"shephi",      pid:"shobal-s",name:"Shephi",      ref:"1Ch 1:40"},
  {id:"onam-s",      pid:"shobal-s",name:"Onam",        ref:"1Ch 1:40"},
  {id:"aiah",        pid:"zibeon",  name:"Aiah",        ref:"1Ch 1:40"},
  {id:"anah-z",      pid:"zibeon",  name:"Anah",        ref:"1Ch 1:40"},
  {id:"dishon-a",    pid:"anah-s",  name:"Dishon",      ref:"1Ch 1:41"},
  {id:"hamran",      pid:"dishon-a",name:"Hamran",      ref:"1Ch 1:41"},
  {id:"eshban",      pid:"dishon-a",name:"Eshban",      ref:"1Ch 1:41"},
  {id:"ithran",      pid:"dishon-a",name:"Ithran",      ref:"1Ch 1:41"},
  {id:"cheran",      pid:"dishon-a",name:"Cheran",      ref:"1Ch 1:41"},
  {id:"bilhan",      pid:"ezer-s",  name:"Bilhan",      ref:"1Ch 1:42"},
  {id:"zaavan",      pid:"ezer-s",  name:"Zaavan",      ref:"1Ch 1:42"},
  {id:"jaakan",      pid:"ezer-s",  name:"Jaakan",      ref:"1Ch 1:42"},
  {id:"uz-d",        pid:"dishan",  name:"Uz",          ref:"1Ch 1:42"},
  {id:"aran",        pid:"dishan",  name:"Aran",        ref:"1Ch 1:42"},

  // ── SONS OF ISRAEL (1Ch 2:1-2) ──────────────────────────────────────────
  {id:"reuben",      pid:"israel",  name:"Reuben",      ref:"1Ch 2:1"},
  {id:"simeon",      pid:"israel",  name:"Simeon",      ref:"1Ch 2:1"},
  {id:"levi",        pid:"israel",  name:"Levi",        ref:"1Ch 2:1"},
  {id:"judah",       pid:"israel",  name:"Judah",       ref:"1Ch 2:1",  spine:true},
  {id:"issachar",    pid:"israel",  name:"Issachar",    ref:"1Ch 2:1"},
  {id:"zebulun",     pid:"israel",  name:"Zebulun",     ref:"1Ch 2:2"},
  {id:"dan",         pid:"israel",  name:"Dan",         ref:"1Ch 2:2"},
  {id:"joseph",      pid:"israel",  name:"Joseph",      ref:"1Ch 2:2"},
  {id:"benjamin",    pid:"israel",  name:"Benjamin",    ref:"1Ch 2:2"},
  {id:"naphtali",    pid:"israel",  name:"Naphtali",    ref:"1Ch 2:2"},
  {id:"gad",         pid:"israel",  name:"Gad",         ref:"1Ch 2:2"},
  {id:"asher",       pid:"israel",  name:"Asher",       ref:"1Ch 2:2"},

  // ── JUDAH'S LINE (1Ch 2:3-55) ───────────────────────────────────────────
  {id:"er-j",        pid:"judah",   name:"Er",          ref:"1Ch 2:3",  note:"wicked; killed by God"},
  {id:"onan",        pid:"judah",   name:"Onan",        ref:"1Ch 2:3"},
  {id:"shelah-j",    pid:"judah",   name:"Shelah",      ref:"1Ch 2:3"},
  {id:"zerah-j",     pid:"judah",   name:"Zerah",       ref:"1Ch 2:4",  note:"by Tamar"},
  {id:"perez",       pid:"judah",   name:"Perez",       ref:"1Ch 2:4",  spine:true, note:"by Tamar"},

  // Zerah's sons (1Ch 2:6-7)
  {id:"zimri",       pid:"zerah-j", name:"Zimri",       ref:"1Ch 2:6"},
  {id:"ethan",       pid:"zerah-j", name:"Ethan",       ref:"1Ch 2:6"},
  {id:"heman-z",     pid:"zerah-j", name:"Heman",       ref:"1Ch 2:6"},
  {id:"calcol",      pid:"zerah-j", name:"Calcol",      ref:"1Ch 2:6"},
  {id:"dara",        pid:"zerah-j", name:"Dara",        ref:"1Ch 2:6"},
  {id:"carmi-z",     pid:"zerah-j", name:"Carmi",       ref:"1Ch 2:7"},
  {id:"azariah-e",   pid:"ethan",   name:"Azariah",     ref:"1Ch 2:8"},
  {id:"achar",       pid:"carmi-z", name:"Achar",       ref:"1Ch 2:7",  note:"the troubler of Israel"},

  // Perez's sons (1Ch 2:5)
  {id:"hamul",       pid:"perez",   name:"Hamul",       ref:"1Ch 2:5"},
  {id:"hezron",      pid:"perez",   name:"Hezron",      ref:"1Ch 2:5",  spine:true},

  // ── HEZRON'S THREE SONS (1Ch 2:9) ───────────────────────────────────────
  {id:"jerahmeel",   pid:"hezron",  name:"Jerahmeel",   ref:"1Ch 2:9"},
  {id:"caleb-h",     pid:"hezron",  name:"Caleb",       ref:"1Ch 2:9",  note:"also called Chelubai"},
  {id:"ram-h",       pid:"hezron",  name:"Ram",         ref:"1Ch 2:9",  spine:true},

  // ── JERAHMEEL'S LINE (1Ch 2:25-41) ─────────────────────────────────────
  {id:"ram-j",       pid:"jerahmeel",name:"Ram",        ref:"1Ch 2:25", note:"firstborn of Jerahmeel"},
  {id:"bunah",       pid:"jerahmeel",name:"Bunah",      ref:"1Ch 2:25"},
  {id:"oren",        pid:"jerahmeel",name:"Oren",       ref:"1Ch 2:25"},
  {id:"ozem-j",      pid:"jerahmeel",name:"Ozem",       ref:"1Ch 2:25"},
  {id:"ahijah-j",    pid:"jerahmeel",name:"Ahijah",     ref:"1Ch 2:25"},
  {id:"onam-j",      pid:"jerahmeel",name:"Onam",       ref:"1Ch 2:26", note:"by wife Atarah"},
  {id:"maaz",        pid:"ram-j",   name:"Maaz",        ref:"1Ch 2:27"},
  {id:"jamin-j",     pid:"ram-j",   name:"Jamin",       ref:"1Ch 2:27"},
  {id:"eker",        pid:"ram-j",   name:"Eker",        ref:"1Ch 2:27"},
  {id:"shammai-o",   pid:"onam-j",  name:"Shammai",     ref:"1Ch 2:28"},
  {id:"jada",        pid:"onam-j",  name:"Jada",        ref:"1Ch 2:28"},
  {id:"nadab-sh",    pid:"shammai-o",name:"Nadab",      ref:"1Ch 2:28"},
  {id:"abishur",     pid:"shammai-o",name:"Abishur",    ref:"1Ch 2:28"},
  {id:"ahban",       pid:"abishur", name:"Ahban",       ref:"1Ch 2:29"},
  {id:"molid",       pid:"abishur", name:"Molid",       ref:"1Ch 2:29"},
  {id:"seled",       pid:"nadab-sh",name:"Seled",       ref:"1Ch 2:30", note:"died without children"},
  {id:"appaim",      pid:"nadab-sh",name:"Appaim",      ref:"1Ch 2:30"},
  {id:"ishi",        pid:"appaim",  name:"Ishi",        ref:"1Ch 2:31"},
  {id:"sheshan",     pid:"ishi",    name:"Sheshan",     ref:"1Ch 2:31", note:"had no sons, only daughters"},
  {id:"ahlai",       pid:"sheshan", name:"Ahlai",       ref:"1Ch 2:31"},
  {id:"dau-jarha",   pid:"sheshan", name:"daughter → Jarha", ref:"1Ch 2:34", note:"gave daughter to Jarha (Egyptian servant)"},
  {id:"attai",       pid:"dau-jarha",name:"Attai",      ref:"1Ch 2:35"},
  {id:"nathan-a",    pid:"attai",   name:"Nathan",      ref:"1Ch 2:36"},
  {id:"zabad",       pid:"nathan-a",name:"Zabad",       ref:"1Ch 2:36"},
  {id:"ephlal",      pid:"zabad",   name:"Ephlal",      ref:"1Ch 2:37"},
  {id:"obed-e",      pid:"ephlal",  name:"Obed",        ref:"1Ch 2:37"},
  {id:"jehu-o",      pid:"obed-e",  name:"Jehu",        ref:"1Ch 2:38"},
  {id:"azariah-j",   pid:"jehu-o",  name:"Azariah",     ref:"1Ch 2:38"},
  {id:"helez",       pid:"azariah-j",name:"Helez",      ref:"1Ch 2:39"},
  {id:"eleasah",     pid:"helez",   name:"Eleasah",     ref:"1Ch 2:39"},
  {id:"sismai",      pid:"eleasah", name:"Sismai",      ref:"1Ch 2:40"},
  {id:"shallum-si",  pid:"sismai",  name:"Shallum",     ref:"1Ch 2:40"},
  {id:"jekamiah",    pid:"shallum-si",name:"Jekamiah",  ref:"1Ch 2:41"},
  {id:"elishama",    pid:"jekamiah",name:"Elishama",    ref:"1Ch 2:41"},
  {id:"jether",      pid:"jada",    name:"Jether",      ref:"1Ch 2:32", note:"died without children"},
  {id:"jonathan-jd", pid:"jada",    name:"Jonathan",    ref:"1Ch 2:32"},
  {id:"peleth",      pid:"jonathan-jd",name:"Peleth",   ref:"1Ch 2:33"},
  {id:"zaza",        pid:"jonathan-jd",name:"Zaza",     ref:"1Ch 2:33"},

  // ── CALEB'S LINE (1Ch 2:18-20, 42-55) ───────────────────────────────────
  {id:"jesher",      pid:"caleb-h", name:"Jesher",      ref:"1Ch 2:18", note:"by Azubah"},
  {id:"shobab",      pid:"caleb-h", name:"Shobab",      ref:"1Ch 2:18", note:"by Azubah"},
  {id:"ardon",       pid:"caleb-h", name:"Ardon",       ref:"1Ch 2:18", note:"by Azubah"},
  {id:"hur-c",       pid:"caleb-h", name:"Hur",         ref:"1Ch 2:19", note:"by Ephrath"},
  {id:"segub",       pid:"caleb-h", name:"Segub",       ref:"1Ch 2:21", note:"by daughter of Machir; Hezron was 60"},
  {id:"mesha-c",     pid:"caleb-h", name:"Mesha",       ref:"1Ch 2:42", note:"father of Ziph"},
  {id:"hebron-c",    pid:"caleb-h", name:"Hebron",      ref:"1Ch 2:43"},
  {id:"jahdai-sons", pid:"caleb-h", name:"sons of Jahdai",ref:"1Ch 2:47"},
  {id:"haran-c",     pid:"caleb-h", name:"Haran",       ref:"1Ch 2:46", note:"by Ephah (concubine)"},
  {id:"moza-c",      pid:"caleb-h", name:"Moza",        ref:"1Ch 2:46", note:"by Ephah (concubine)"},
  {id:"gazez-e",     pid:"caleb-h", name:"Gazez",       ref:"1Ch 2:46", note:"by Ephah (concubine)"},
  {id:"sheber",      pid:"caleb-h", name:"Sheber",      ref:"1Ch 2:48", note:"by Maacah (concubine)"},
  {id:"tirhanah",    pid:"caleb-h", name:"Tirhanah",    ref:"1Ch 2:48", note:"by Maacah (concubine)"},
  {id:"shaaph-c",    pid:"caleb-h", name:"Shaaph",      ref:"1Ch 2:49", note:"father of Madmannah"},
  {id:"sheva-c",     pid:"caleb-h", name:"Sheva",       ref:"1Ch 2:49", note:"father of Machbena and Gibea"},
  {id:"achsah",      pid:"caleb-h", name:"Achsah",      ref:"1Ch 2:49", note:"daughter of Caleb"},
  {id:"uri-h",       pid:"hur-c",   name:"Uri",         ref:"1Ch 2:20"},
  {id:"shobal-h",    pid:"hur-c",   name:"Shobal",      ref:"1Ch 2:50", note:"father of Kiriath Jearim"},
  {id:"salma-h",     pid:"hur-c",   name:"Salma",       ref:"1Ch 2:51", note:"father of Bethlehem"},
  {id:"hareph",      pid:"hur-c",   name:"Hareph",      ref:"1Ch 2:51", note:"father of Beth Gader"},
  {id:"bezalel",     pid:"uri-h",   name:"Bezalel",     ref:"1Ch 2:20"},
  {id:"jair",        pid:"segub",   name:"Jair",        ref:"1Ch 2:22", note:"23 cities in Gilead"},
  {id:"korah-h",     pid:"hebron-c",name:"Korah",       ref:"1Ch 2:43"},
  {id:"tappuah",     pid:"hebron-c",name:"Tappuah",     ref:"1Ch 2:43"},
  {id:"rekem-h",     pid:"hebron-c",name:"Rekem",       ref:"1Ch 2:43"},
  {id:"shema-h",     pid:"hebron-c",name:"Shema",       ref:"1Ch 2:43"},
  {id:"shammai-r",   pid:"rekem-h", name:"Shammai",     ref:"1Ch 2:44"},
  {id:"maon",        pid:"shammai-r",name:"Maon",       ref:"1Ch 2:45", note:"father of Beth Zur"},
  {id:"raham",       pid:"shema-h", name:"Raham",       ref:"1Ch 2:44", note:"father of Jorkeam"},
  {id:"regem",       pid:"jahdai-sons",name:"Regem",    ref:"1Ch 2:47"},
  {id:"jothan",      pid:"jahdai-sons",name:"Jothan",   ref:"1Ch 2:47"},
  {id:"geshan",      pid:"jahdai-sons",name:"Geshan",   ref:"1Ch 2:47"},
  {id:"pelet-jd",    pid:"jahdai-sons",name:"Pelet",    ref:"1Ch 2:47"},
  {id:"ephah-jd",    pid:"jahdai-sons",name:"Ephah",    ref:"1Ch 2:47"},
  {id:"shaaph-jd",   pid:"jahdai-sons",name:"Shaaph",   ref:"1Ch 2:47"},
  {id:"gazez-h",     pid:"haran-c", name:"Gazez",       ref:"1Ch 2:46"},

  // ── RAM'S LINE — THE DAVIDIC SPINE (1Ch 2:10-17) ────────────────────────
  {id:"amminadab",   pid:"ram-h",   name:"Amminadab",   ref:"1Ch 2:10", spine:true},
  {id:"nahshon",     pid:"amminadab",name:"Nahshon",    ref:"1Ch 2:10", spine:true, note:"prince of the children of Judah"},
  {id:"salma-n",     pid:"nahshon", name:"Salma",       ref:"1Ch 2:11", spine:true},
  {id:"boaz",        pid:"salma-n", name:"Boaz",        ref:"1Ch 2:11", spine:true},
  {id:"obed",        pid:"boaz",    name:"Obed",        ref:"1Ch 2:12", spine:true},
  {id:"jesse",       pid:"obed",    name:"Jesse",       ref:"1Ch 2:12", spine:true},
  {id:"eliab",       pid:"jesse",   name:"Eliab",       ref:"1Ch 2:13", note:"firstborn"},
  {id:"abinadab",    pid:"jesse",   name:"Abinadab",    ref:"1Ch 2:13"},
  {id:"shimea",      pid:"jesse",   name:"Shimea",      ref:"1Ch 2:13"},
  {id:"nethanel",    pid:"jesse",   name:"Nethanel",    ref:"1Ch 2:14"},
  {id:"raddai",      pid:"jesse",   name:"Raddai",      ref:"1Ch 2:14"},
  {id:"ozem-jss",    pid:"jesse",   name:"Ozem",        ref:"1Ch 2:15"},
  {id:"david",       pid:"jesse",   name:"David",       ref:"1Ch 2:15", spine:true, david:true, note:"seventh son of Jesse; king of Israel"},
  {id:"zeruiah",     pid:"jesse",   name:"Zeruiah",     ref:"1Ch 2:16", note:"daughter of Jesse"},
  {id:"abigail-j",   pid:"jesse",   name:"Abigail",     ref:"1Ch 2:16", note:"daughter of Jesse"},
  {id:"abishai",     pid:"zeruiah", name:"Abishai",     ref:"1Ch 2:16"},
  {id:"joab",        pid:"zeruiah", name:"Joab",        ref:"1Ch 2:16"},
  {id:"asahel",      pid:"zeruiah", name:"Asahel",      ref:"1Ch 2:16"},
  {id:"amasa",       pid:"abigail-j",name:"Amasa",      ref:"1Ch 2:17", note:"father: Jether the Ishmaelite"},

];
